title: Cirrostratus
description: AWS & DevOps Consulting | Tech Leadership | Infrastructure as Code
remote_theme: pages-themes/hacker@v0.2.0
url: "https://cirrostratuscloud.github.io"
baseurl: "/website-public"

author:
  name: Cirrostratus
  email: contact@cirrostratus.cloud

# Navigation
navigation:
  - title: Home
    url: /
  - title: Services
    url: /services
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Contact
    url: /contact

# Blog settings
permalink: /:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

# SEO
linkedin:
  username: yannickvanrooyen/
github:
  username: yannickvr

# Collections
collections:
  posts:
    output: true
    permalink: /:title/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge